version: '3'

services:
  mysqlsrv:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "database"
    ports:
      - "3305:3305"
    volumes:
      - /Users/warsilva/Desktop/mysql:/var/lib/mysql
    networks:
      - mysql-compose-network

#  adminer:
#    image: adminer
#    ports:
#      - 8080:8080
#    networks:
#      - mysql-compose-network

networks:
  mysql-compose-network:
    driver: bridge
