version: "3.9"

services:
  db:
    image: mysql:8
#    volumes:
#      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: datatest
      MYSQL_USER: user0
      MYSQL_PASSWORD: root
    ports:
    - "3306:3306"
